# Generated by Django 4.1.3 on 2022-11-28 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jawaban',
            name='snippet',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='pertanyaan',
            name='snippet',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
